version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - my_network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - my_network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: solve_db
      MYSQL_USER: meklad
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: meklad
      PMA_PASSWORD: password
    ports:
      - "8090:80"
    depends_on:
      - mysql
    networks:
      - my_network

  composer:
    image: composer
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - my_network

networks:
    my_network:
        driver: bridge
